"""Small, deterministic curation pipeline used by the Flyte workflow and CLI."""

from __future__ import annotations

import ast
import hashlib
import json
import re
from collections import Counter
from datetime import UTC, datetime
from pathlib import Path
from typing import Iterable


SECRET_RE = re.compile(r"(?i)(api[_-]?key|secret|password|token)\s*[:=]\s*['\"][^'\"]{8,}|AKIA[0-9A-Z]{16}")
GENERATED_RE = re.compile(r"(?i)(generated by|do not edit|auto-generated|webpack|protobuf compiler)")


def _norm(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def _hash(text: str) -> str:
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _shingles(text: str) -> set[str]:
    tokens = re.findall(r"\w+|[^\w\s]", text)
    return {" ".join(tokens[i:i + 5]) for i in range(max(1, len(tokens) - 4))}


def _similar(left: set[str], right: set[str], threshold: float = 0.92) -> bool:
    return len(left & right) / max(1, len(left | right)) >= threshold


def load_jsonl(path: str | Path) -> list[dict]:
    return [json.loads(line) for line in Path(path).read_text(encoding="utf-8").splitlines() if line.strip()]


def exact_deduplicate(documents: Iterable[dict]) -> list[dict]:
    seen: set[str] = set()
    result = []
    for document in documents:
        key = _hash(document.get("content", ""))
        if key in seen:
            continue
        seen.add(key)
        result.append({**document, "content_hash": _hash(document.get("content", ""))})
    return result


def near_deduplicate(documents: Iterable[dict], threshold: float = 0.92) -> list[dict]:
    """Use bounded token shingles for a small exercise-sized near-dedup pass."""
    kept: list[dict] = []
    signatures: list[set[str]] = []
    for document in documents:
        shingles = _shingles(document.get("content", ""))
        if any(
            _similar(shingles, previous, threshold)
            for previous in signatures
        ):
            continue
        signatures.append(shingles)
        kept.append(document)
    return kept


def quality_filter(documents: Iterable[dict]) -> tuple[list[dict], list[dict]]:
    accepted, rejected = [], []
    for document in documents:
        content = document.get("content", "")
        reason = None
        path_parts = set(str(document.get("file_path") or document.get("path") or document.get("repo_path") or "").replace("\\", "/").lower().split("/"))
        if not isinstance(content, str) or not content.strip() or "\x00" in content:
            reason = "malformed"
        elif document.get("is_vendor") or path_parts & {"vendor", "node_modules", "third_party", "third-party"}:
            reason = "vendor"
        elif GENERATED_RE.search(content):
            reason = "generated"
        elif SECRET_RE.search(content):
            reason = "secret"
        elif document.get("language", "").lower() == "python":
            try:
                ast.parse(content)
            except (SyntaxError, ValueError):
                reason = "malformed_python"
        if reason:
            rejected.append({**document, "rejection_reason": reason})
        else:
            accepted.append(document)
    return accepted, rejected


def decontaminate(documents: Iterable[dict], evaluation_documents: Iterable[dict]) -> tuple[list[dict], list[dict]]:
    eval_texts = {_norm(d.get("content", "")) for d in evaluation_documents if d.get("content", "").strip()}
    clean, removed = [], []
    for document in documents:
        text = _norm(document.get("content", ""))
        if text in eval_texts or any(len(reference) >= 40 and reference in text for reference in eval_texts):
            removed.append({**document, "rejection_reason": "evaluation_contamination"})
        else:
            clean.append(document)
    return clean, removed


def cross_dataset_deduplicate(documents: Iterable[dict], organic: Iterable[dict]) -> tuple[list[dict], list[dict]]:
    organic = list(organic)
    organic_hashes = {_hash(_norm(d.get("content", ""))) for d in organic}
    signatures = [_shingles(d.get("content", "")) for d in organic]
    seen = set(organic_hashes)
    kept, removed = [], []
    for document in documents:
        key = _hash(_norm(document.get("content", "")))
        signature = _shingles(document.get("content", ""))
        if key in seen or any(_similar(signature, previous) for previous in signatures):
            removed.append({**document, "rejection_reason": "duplicate_against_organic_or_branch"})
        else:
            seen.add(key)
            signatures.append(signature)
            kept.append(document)
    return kept, removed


def allocate_branch_quotas(n: int, branches: int = 6) -> list[int]:
    total = round(1.5 * n)
    base, remainder = divmod(total, branches)
    return [base + (i < remainder) for i in range(branches)]


def select_branch_parents(
    organic: list[dict], model: str, method: str, *, codetrace_limit: int = 1000
) -> list[dict]:
    if codetrace_limit < 0:
        raise ValueError("codetrace_limit must be nonnegative")
    if method == "codetrace":
        # Round-robin by repository; both models receive the same paired cohort.
        by_repo: dict[str, list[dict]] = {}
        for document in organic:
            if document.get("language", "").lower() != "python":
                continue
            repo = str(document.get("repo_id") or document.get("repo_path") or document["document_id"])
            by_repo.setdefault(repo, []).append(document)
        for documents in by_repo.values():
            documents.sort(key=lambda d: d["document_id"])
        selected: list[dict] = []
        offset = 0
        while len(selected) < codetrace_limit:
            progressed = False
            for repo in sorted(by_repo):
                if offset < len(by_repo[repo]):
                    selected.append(by_repo[repo][offset])
                    progressed = True
                    if len(selected) == codetrace_limit:
                        break
            if not progressed:
                break
            offset += 1
        return selected
    models = ["qwen_coder", "codegemma"]
    methods = ["swallowcode", "codedev", "codeqa"]
    index = list((m, t) for m in models for t in methods).index((model, method))
    quota = allocate_branch_quotas(len(organic), len(models) * len(methods))[index]
    language_counts = Counter(d["language"] for d in organic)
    if not organic:
        return []
    allocations = {language: quota * count // len(organic) for language, count in language_counts.items()}
    for language in sorted(language_counts, key=lambda lang: (-(quota * language_counts[lang] % len(organic)), lang))[:quota - sum(allocations.values())]:
        allocations[language] += 1
    selected: list[dict] = []
    offsets = Counter()
    while len(selected) < quota:
        progressed = False
        for language in sorted(language_counts):
            candidates = [d for d in organic if d["language"] == language]
            if offsets[language] < len(candidates):
                if offsets[language] >= allocations[language]:
                    continue
                selected.append(candidates[offsets[language]])
                offsets[language] += 1
                progressed = True
                if len(selected) == quota:
                    break
        if not progressed:
            break
    return selected


def generate_mock(parent: dict, model: str, method: str, prompt_version: str = "v1") -> dict:
    content = parent["content"]
    if method == "swallowcode":
        generated = f"# rewritten example ({model})\n{content}"
    elif method == "codedev":
        generated = (
            f"Generator: {model}\nDevelopment task: Improve the behavior of this {parent['language']} component.\n"
            f"Source:\n{content}\nSolution:\n{content}"
        )
    elif method == "codeqa":
        generated = (
            f"Generator: {model}\nQuestion: What does this {parent['language']} code do, and what edge cases matter?\n"
            f"Code:\n{content}\nAnswer:\nThe implementation shown above defines the behavior; verify its inputs and boundary cases."
        )
    elif method == "codetrace":
        generated = (
            f"# MOCK_CODETRACE model={model}; execution was not run\n"
            f"Code:\n```python\n{content}\n```\n\n"
            "Test input:\n```python\n# mocked test harness\n```\n\n"
            "Observed execution trace:\nMOCKED — no runtime evidence was produced."
        )
    else:
        raise ValueError(f"unknown generation method: {method}")
    return {
        **parent,
        "document_id": f"synthetic:{model}:{method}:{parent['document_id']}",
        "parent_document_id": parent["document_id"],
        "repo_id": parent.get("repo_id"),
        "mock": True,
        "content": generated,
        "language": parent["language"],
        "repo_path": parent.get("repo_path"),
        "license_type": parent.get("license_type"),
        "source_dataset": parent.get("source_dataset"),
        "model": model,
        "model_version": {"qwen_coder": "Qwen/Qwen2.5-Coder-7B-Instruct", "codegemma": "google/codegemma-7b-it"}[model],
        "method": method,
        "prompt_version": prompt_version,
        "synthetic": True,
        "token_count": len(generated.split()),
        "execution_checked": False,
        "trace_deterministic": None,
    }


def generate_one_branch(
    organic: list[dict], model: str, method: str, *, mock: bool = True,
    codetrace_limit: int = 1000,
) -> list[dict]:
    if not mock:
        raise RuntimeError("Real adapters are configured separately; mock=False is not implemented here")
    selected = select_branch_parents(organic, model, method, codetrace_limit=codetrace_limit)
    return [generate_mock(d, model, method) for d in selected]


def generate_branches(
    organic: list[dict], *, mock: bool = True, codetrace_limit: int = 1000
) -> list[dict]:
    return [
        document
        for model in ("qwen_coder", "codegemma")
        for method in ("swallowcode", "codedev", "codeqa", "codetrace")
        for document in generate_one_branch(
            organic, model, method, mock=mock, codetrace_limit=codetrace_limit
        )
    ]


def validate_generated(documents: Iterable[dict]) -> tuple[list[dict], list[dict]]:
    accepted, rejected = [], []
    for document in documents:
        content = document.get("content", "")
        syntax_valid, correctness_verified = None, False
        reason = None
        if not isinstance(content, str) or not content.strip() or "\x00" in content:
            reason = "malformed"
        elif SECRET_RE.search(content):
            reason = "secret"
        check_kind = "not_applicable"
        if document.get("method") in {"codedev", "codeqa", "codetrace"}:
            # The record is pretraining text; its embedded code is validated by
            # the parent-document check rather than parsing the prose wrapper.
            check_kind = "runtime_trace" if document.get("method") == "codetrace" else "embedded_code_unchecked"
            blocks = re.findall(r"```(?:python|py)\s*\n(.*?)```", content, re.DOTALL)
            if blocks:
                check_kind = "python_ast_embedded"
                try:
                    for block in blocks:
                        ast.parse(block)
                    syntax_valid = True
                except (SyntaxError, ValueError):
                    syntax_valid = False
            if document.get("method") == "codetrace" and not document.get("mock") and not (document.get("execution_checked") and document.get("trace_deterministic")):
                reason = "missing_runtime_trace_evidence"
        elif document.get("language") == "Python":
            check_kind = "python_ast"
            try:
                ast.parse(content)
                syntax_valid = True
            except SyntaxError:
                syntax_valid = False
        result = {**document, "validation": {"syntax_valid": syntax_valid, "syntax_check": check_kind, "correctness_verified": correctness_verified, "execution_checked": bool(document.get("execution_checked")), "trace_deterministic": document.get("trace_deterministic")}}
        if reason or syntax_valid is False:
            result["rejection_reason"] = reason or "syntax_invalid"
            rejected.append(result)
        else:
            accepted.append(result)
    return accepted, rejected


def export_dataset(
    organic: list[dict], synthetic: list[dict], output_dir: str | Path,
    *, codetrace_target_per_model: int = 1000,
) -> dict:
    out = Path(output_dir)
    out.mkdir(parents=True, exist_ok=True)
    if (out / "train-00000.jsonl").exists() or (out / "manifest.json").exists():
        raise FileExistsError(f"Refusing to overwrite dataset in {out}")
    merged = organic + synthetic
    shard = out / "train-00000.jsonl"
    with shard.open("w", encoding="utf-8") as handle:
        for document in merged:
            document = {**document, "token_count": len(document.get("content", "").split())}
            handle.write(json.dumps(document, ensure_ascii=False) + "\n")
    base_synthetic = [d for d in synthetic if d.get("method") != "codetrace"]
    codetrace_synthetic = [d for d in synthetic if d.get("method") == "codetrace"]
    base_target = round(1.5 * len(organic))
    codetrace_target = 2 * codetrace_target_per_model
    manifest = {
        "created_at_utc": datetime.now(UTC).isoformat(),
        "token_count_method": "whitespace_estimate_not_model_tokens",
        "organic_documents": len(organic),
        "synthetic_documents": len(synthetic),
        "base_synthetic_target_documents": base_target,
        "base_synthetic_accepted_documents": len(base_synthetic),
        "base_synthetic_shortfall_documents": max(0, base_target - len(base_synthetic)),
        "codetrace_pilot_target_per_model": codetrace_target_per_model,
        "codetrace_pilot_target_documents": codetrace_target,
        "codetrace_pilot_accepted_documents": len(codetrace_synthetic),
        "codetrace_pilot_shortfall_documents": max(0, codetrace_target - len(codetrace_synthetic)),
        "synthetic_target_documents": base_target + codetrace_target,
        "synthetic_shortfall_documents": max(0, base_target + codetrace_target - len(synthetic)),
        "total_documents": len(merged),
        "organic_token_count": sum(d.get("token_count", len(d.get("content", "").split())) for d in organic),
        "synthetic_token_count": sum(d.get("token_count", len(d.get("content", "").split())) for d in synthetic),
        "synthetic_by_model_method": {
            f"{model}/{method}": count
            for (model, method), count in Counter((d["model"], d["method"]) for d in synthetic).items()
        },
        "shards": [shard.name],
    }
    (out / "manifest.json").write_text(json.dumps(manifest, indent=2, default=str) + "\n", encoding="utf-8")
    return manifest
