from collections import Counter
from pathlib import Path

import pytest

from code_data_curation.filtering import QUALITY_RULES, first_rejection, measure_quality
from code_data_curation.pipeline import load_jsonl, quality_filter


VALID_SNIPPETS = {
    "C": "int add(int left, int right) { return left + right; }\n",
    "C#": "class Counter { int Add(int left, int right) { return left + right; } }\n",
    "C++": "int add(int left, int right) { return left + right; }\n",
    "Dart": "int add(int left, int right) { return left + right; }\n",
    "Go": "package sample\nfunc add(left int, right int) int { return left + right }\n",
    "Java": "class Counter { int add(int left, int right) { return left + right; } }\n",
    "JavaScript": "function add(left, right) { return left + right; }\n",
    "Kotlin": "fun add(left: Int, right: Int): Int { return left + right }\n",
    "PHP": "<?php\nfunction add($left, $right) { return $left + $right; }\n",
    "Python": "def add(left, right):\n    return left + right\n",
    "Ruby": "def add(left, right)\n  left + right\nend\n",
    "Rust": "fn add(left: i32, right: i32) -> i32 { left + right }\n",
    "Scala": "object Counter { def add(left: Int, right: Int): Int = left + right }\n",
    "Swift": "func add(_ left: Int, _ right: Int) -> Int { return left + right }\n",
    "TypeScript": "function add(left: number, right: number): number { return left + right; }\n",
}


@pytest.mark.parametrize(("language", "content"), VALID_SNIPPETS.items())
def test_tree_sitter_parses_each_supported_language(language, content):
    signals = measure_quality(content, language)
    assert signals["parse_supported"] is True
    assert signals["parse_error"] is False


def _passing_signals():
    return {
        "num_characters": 500,
        "num_bytes": 500,
        "num_words": 80,
        "num_lines": 20,
        "mean_word_length": 5.0,
        "max_line_length": 80,
        "mean_line_length": 25.0,
        "replacement_character_fraction": 0.0,
        "duplicate_line_fraction": 0.0,
        "top_2gram_fraction": 0.0,
        "top_3gram_fraction": 0.0,
        "top_4gram_fraction": 0.0,
        "alphabetic_fraction": 0.60,
        "numeric_fraction": 0.0,
        "whitespace_fraction": 0.20,
        "comment_fraction": 0.0,
        "encoded_data_fraction": 0.0,
        "long_string_fraction": 0.0,
        "parse_error": False,
    }


@pytest.mark.parametrize(
    ("signal", "comparison", "threshold", "reason"),
    QUALITY_RULES,
)
def test_rule_threshold_boundaries(signal, comparison, threshold, reason):
    signals = _passing_signals()
    signals[signal] = threshold
    assert first_rejection(signals) is None
    signals[signal] = (
        threshold - 1 if comparison == "min" and isinstance(threshold, int)
        else threshold - 0.001 if comparison == "min"
        else threshold + 1 if comparison == "max" and isinstance(threshold, int)
        else threshold + 0.001 if comparison == "max"
        else True
    )
    rejection = first_rejection(signals)
    assert rejection is not None
    assert rejection[:2] == (reason, signal)
    assert rejection[2] == signals[signal]
    assert rejection[3] == threshold


def test_rejections_include_precise_metadata():
    repetitive = "\n".join(["result = calculate repeated value"] * 12)
    malformed = "\n".join(
        f"value_{index} = source_{index} + offset_{index}" for index in range(12)
    ) + "\ndef bad(:\n"
    generated = "generated by a tool"
    secret = "api_key = 'abcdefghijk'"
    documents = [
        {"document_id": "repeat", "language": "Python", "content": repetitive},
        {"document_id": "malformed", "language": "Python", "content": malformed},
        {"document_id": "generated", "language": "Python", "content": generated},
        {"document_id": "vendor", "language": "Python", "content": generated, "file_path": "src/vendor/a.py"},
        {"document_id": "secret", "language": "Python", "content": secret},
    ]
    accepted, rejected = quality_filter(documents)
    assert accepted == []
    by_id = {row["document_id"]: row for row in rejected}
    assert by_id["repeat"]["rejection_reason"] == "too_many_duplicate_lines"
    assert by_id["repeat"]["rejection_signal"] == "duplicate_line_fraction"
    assert by_id["generated"]["rejection_signal"] == "generated_marker"
    assert by_id["vendor"]["rejection_signal"] == "is_vendor"
    assert by_id["secret"]["rejection_signal"] == "secret_marker"
    assert by_id["malformed"]["rejection_signal"] == "parse_error"
    assert by_id["malformed"]["quality_signals"]["parse_error"] is True
    assert all("rejection_value" in row and "rejection_threshold" in row for row in rejected)


def test_sample_retains_at_least_half_of_every_language():
    rows = load_jsonl("data/raw/stack-v3-sample.jsonl")
    accepted, _ = quality_filter(rows)
    totals = Counter(row["language"] for row in rows)
    kept = Counter(row["language"] for row in accepted)
    assert set(totals) == set(VALID_SNIPPETS)
    assert all(kept[language] * 2 >= total for language, total in totals.items())


def test_workflow_diagram_names_and_attributes_the_three_cleaning_steps():
    html = Path("docs/workflow.html").read_text(encoding="utf-8")
    start = html.index('aria-label="Sequential cleaning steps"')
    end = html.index('<div class="stage">', start)
    sequence = html[start:end]
    assert sequence.count('<article class="card') == 3
    assert sequence.count('class="arrow"') == 2
    assert "Filter · OpenCoder-inspired" in sequence
    assert "https://github.com/OpenCoder-llm/opc_data_filtering" in sequence
    assert "CPU · Batch" in sequence
    assert "Quality score" not in sequence


def test_workflow_diagram_defines_document_output_and_token_ablation():
    html = Path("docs/workflow.html").read_text(encoding="utf-8")
    assert "Published corpus" in html
    assert "the training sampler chooses the token mixture" in html
    assert 'aria-label="Synthetic token mixture ablation"' in html
    assert html.index('aria-label="Synthetic token mixture ablation"') > html.index("</section>")
    assert "outside the Flyte data-curation DAG" in html
    assert "Continued-pretraining (CPT) mixture ablation" in html
    assert "determine whether synthetic code improves a pretrained code model" in html
    assert "continue causal next-token pretraining" in html
    assert "changing only the synthetic-data percentage" in html
    assert "same number of training tokens and the same compute budget" in html
    assert all(term not in html for term in ("SFT", "DPO", "RLVR"))
    assert "tokenizer" + "-token" not in html
    assert all(f"{ratio}% synthetic" in html for ratio in (0, 30, 60, 100))
    assert "without repeating organic tokens" in html
    assert "best synthetic arm with equal total token budgets" in html
    assert all(text not in html for text in (
        "15 languages", "concurrency = 2", "1,000 Python", "≤2,000",
        "1.05B", "2.10B",
    ))
    assert all(text in html for text in ("N documents", "S documents", "N + S documents"))
